#!/usr/bin/env bash
# 2023.01.26 - ducet8@outlook.com

##
# Bash Exports
##
if [[ ${BD_OS,,} == "darwin" ]]; then
    export SHELL=/usr/local/bin/bash  # Brew's bash
    export BASH_SILENCE_DEPRECATION_WARNING=1  # hide macos' 'default shell is now ZSH message on root login'
else
    export SHELL=$(which bash)
fi


##
# bd exports
##
if type bd_ansi &>/dev/null; then
    export -f bd_ansi
fi

##
# Color Exports
##
#if type -P tput &> /dev/null; then
#    tput sgr0 # reset colors
#    export BOLD="$(tput bold 2> /dev/null)"
#    export RESET="$(tput sgr0 2> /dev/null)"
#    # Solarized colors, taken from http://git.io/solarized-colors.
#    export BLACK="$(tput setaf 0 2> /dev/null)"
#    export BLUE="$(tput setaf 33 2> /dev/null)"  # Alternate choice: 4
#    export CYAN="$(tput setaf 37 2> /dev/null)"  # Alternate choice: 6
#    export GREEN="$(tput setaf 64 2> /dev/null)"  # Alternate choice: 2
#    export ORANGE="$(tput setaf 166 2> /dev/null)"
#    export PURPLE="$(tput setaf 125 2> /dev/null)"
#    export RED="$(tput setaf 124 2> /dev/null)"  # Alternate choice: 1
#    export VIOLET="$(tput setaf 61 2> /dev/null)"
#    export WHITE="$(tput setaf 15 2> /dev/null)"  # Alternate choice: 7
#    export YELLOW="$(tput setaf 136 2> /dev/null)"  # Alternate choice: 3
#    export TPUT_BOLD=${BOLD}
#    export TPUT_SETAF_0=${BLACK}
#    export TPUT_SETAF_1=${RED}
#    export TPUT_SETAF_2=${GREEN}
#    export TPUT_SETAF_3=${YELLOW}
#    export TPUT_SETAF_4=${BLUE}
#    export TPUT_SETAF_5=${VIOLET}
#    export TPUT_SETAF_6=${CYAN}
#    export TPUT_SETAF_7=${WHITE}
#    export TPUT_SETAF_8="$(tput setaf 8 2> /dev/null)" # grey
#    export TPUT_SGR0=${RESET}
#    export TPUT_SMSO="$(tput smso 2> /dev/null)" # standout
#else
#    export BOLD=''
#    export RESET="\[\e[0m\]"
#    export BLACK="\[\e[1;30m\]"
#    export RED="\[\e[1;31m\]"
#    export GREEN="\[\e[1;32m\]"
#    export ORANGE="\[\e[1;33m\]"
#    export YELLOW="\[\e[1;33m\]"
#    export BLUE="\[\e[1;34m\]"
#    export PURPLE="\[\e[1;35m\]"
#    export VIOLET="\[\e[1;35m\]"
#    export CYAN="\[\e[1;36m\]"
#    export WHITE="\[\e[1;37m\]"
#    
#fi

##
# Colors for ls Exports
##
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

##
# Custom PATH Exports
##
#export PATH=/usr/local/bin:${BD_HOME}/local/bin:$PATH

##
# EDITOR Exports
##
unset -v EDITOR
Editors=(nvim vim vi)
for Editor in ${Editors[@]}; do
    if type -P ${Editor} &> /dev/null; then
        export EDITOR="$(type -P ${Editor} 2> /dev/null)"
        if [[ "${EDITOR}" == *"vim"* ]] && [ -r "${BD_HOME}/.vimrc" ]; then
            alias vim="HOME=\"${BD_HOME}\" ${EDITOR} --cmd \"let BD_USER='$(whoami)'\" --cmd \"let BD_HOME='${BD_HOME}'\""
        else
            alias vim="${EDITOR}"
        fi
        if type -P vim &> /dev/null; then
            alias vi=vim
        fi
        break
    fi
done
unset -v Editor Editors

##
# Git Exports
##
if type -P git &> /dev/null; then
    export GIT_EDITOR=${EDITOR}
fi

##
# Go Exports
##
if [[ ${BD_OS,,} == "darwin" ]]; then
    export SHELL=/usr/local/bin/bash
    export GOPATH=${HOME}/projects/go
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=${PATH}:${GOROOT}/bin
else
    export GOPATH=${HOME}/go
fi
export GOBIN=${GOPATH}/bin
export PATH=${PATH}:${GOPATH}/bin

# if it's an ssh session export GPG_TTY
if [[ -n "${SSH_CLIENT}" ]] || [[ -n "${SSH_TTY}" ]]; then
	GPG_TTY=$(tty)
	export GPG_TTY
fi

# hidpi for gtk apps
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export QT_DEVICE_PIXEL_RATIO=2

##
# History Exports
##
export HISTSIZE=50000000;
export HISTFILESIZE=${HISTSIZE};
export HISTIGNORE=" *:ls:cd:cd -:cd ~:pwd:exit:date:* --help:* -h:clear:man *:df -*:history *";
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT="[%Y-%m-%d %H:%M:%S] "

export TZ="America/Chicago"

##
# Language Exports - Prefer US English and use UTF-8
##
#export LANG="en_US.UTF-8";
#if [[ ${BD_OS,,} == "darwin" ]]; then
#    export LC_ALL="en_US.UTF-8";
#fi
export LC_COLLATE=POSIX

##
# Man Exports
##
if type -P bat &>/dev/null; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
else
    # Don’t clear the screen after quitting a manual page
    export MANPAGER="less -X";
fi
Man_Paths=()
Man_Paths+=(/usr/local/share/man)
Man_Paths+=(/usr/share/man)
for Man_Path in ${Man_Paths[@]}; do
    if ! [[ "${MANPATH}" =~ (^|:)${Man_Path}($|:) ]]; then
        if [ -r "${Man_Path}" ]; then
            export MANPATH+=":${Man_Path}"
        fi
    fi
done

export TODOTXT_DEFAULT_ACTION=ls

##
# Python Exports
##
if [[ ${BD_OS,,} == "darwin" ]]; then
    export PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:${PATH}"
fi

##
# Subversion Exports
##
if type -P svn &> /dev/null; then
    export SVN_EDITOR=${EDITOR}
fi

##
# TERM Exports (preserve TERM for screen & tmux; handle TERM before prompt)
##
if [ "${TERM}" != "linux" ] && [[ "${TERM}" != *"screen"* ]] && [[ "${TERM}" != *"tmux"* ]]; then
    if [ ${#KONSOLE_DBUS_WINDOW} -gt 0 ] && [ -r /usr/share/terminfo/k/konsole-256color ]; then
        export TERM=konsole-256color # if it's a konsole dbus window then use konsole-256color
    else
        export TERM=xterm-256color
    fi
fi

if [[ "${TERM}" == *"screen"* ]]; then
    if [ -r /usr/share/terminfo/s/screen-256color ] || [ -r /usr/share/terminfo/73/screen-256color ] || [ -r /usr/lib/terminfo/s/screen-256color ]; then
        export TERM=screen-256color
    else
        if [ -r /usr/share/terminfo/s/screen ]; then
            export TERM=screen
        else
            export TERM=ansi
        fi
    fi
fi

# This is mainly for performance; as long as TERM doesn't change then there's no need to run tput every time
if [ "${TERM}" != "${TPUT_TERM}" ] || [ ${#TPUT_TERM} -eq 0 ]; then
    if type -P tput &> /dev/null; then
        export TPUT_TERM=${TERM}
        export TPUT_BOLD="$(tput bold 2> /dev/null)"
    fi
fi

##
# Weather (WTTR) Exports
##
export WTTR_PARAMS=Fu
export WTTR_LOCATION=35209

##
# Uname Exports
##
export Uname_I=$(uname -i 2> /dev/null)

##
# Unique PATH - Deprecated in favor of zz-bd-autopath.sh
##
#OIFS=${IFS}
#IFS=':' read -ra Auto_Path <<< "${PATH}"
#Uniq_Path="./"
#for Dir_Path in "${Auto_Path[@]}"; do
#    if ! [[ "${Uniq_Path}" =~ (^|:)${Dir_Path}($|:) ]]; then
#        if [ -r "${Dir_Path}" ] && [ "${Dir_Path}" != "" ]; then
#            Uniq_Path+=":${Dir_Path}"
#        fi
#    fi
#done
#unset -v Dir_Path
#IFS=${OIFS}

#export PATH="${Uniq_Path}"

#unset -v Auto_Path
#unset -v Uniq_Path

##
# Local Exports
##
if  [[ -r ${HOME}/exports_local ]] && [[ -f ${HOME}/exports_local ]]; then
    source ${HOME}/exports_local
fi
